# Generated by Django 5.0.8 on 2024-10-04 03:50

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('tier', models.CharField(choices=[('tier 1', 'Cấp độ 1'), ('tier 2', 'Cấp độ 2'), ('tier 3', 'Cấp độ 3')], max_length=50)),
                ('fax', models.IntegerField(blank=True, null=True)),
                ('contact_list', models.JSONField(blank=True, default=dict, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('Phuy', 'Phuy'), ('Thùng', 'Thùng'), ('Cơ Khí Ô Tô', 'Cơ Khí Ô Tô')], max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCustomer',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('tier', models.CharField(choices=[('tier 1', 'Cấp độ 1'), ('tier 2', 'Cấp độ 2'), ('tier 3', 'Cấp độ 3')], max_length=50)),
                ('fax', models.IntegerField(blank=True, null=True)),
                ('contact_list', models.JSONField(blank=True, default=dict, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Customer',
                'verbose_name_plural': 'historical Customers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('Phuy', 'Phuy'), ('Thùng', 'Thùng'), ('Cơ Khí Ô Tô', 'Cơ Khí Ô Tô')], max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Product',
                'verbose_name_plural': 'historical Products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProductOrder',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_urgent', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Mở'), ('Processing', 'Đang xử lý đơn hàng'), ('BuyingMaterial', 'Lên Kế Hoạch Sản Xuất'), ('InProduction', 'Đang Sản Xuất'), ('Delivering', 'Giao Hàng'), ('Completed', 'Hoàn Thành'), ('Cancelled', 'Cancelled')], default='Open', max_length=50)),
                ('note', models.CharField(blank=True, default='', max_length=2000)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.customer')),
                ('deliverer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('logistic_staff', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale_staff', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Product Order',
                'verbose_name_plural': 'historical Product Orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_urgent', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Mở'), ('Processing', 'Đang xử lý đơn hàng'), ('BuyingMaterial', 'Lên Kế Hoạch Sản Xuất'), ('InProduction', 'Đang Sản Xuất'), ('Delivering', 'Giao Hàng'), ('Completed', 'Hoàn Thành'), ('Cancelled', 'Cancelled')], default='Open', max_length=50)),
                ('note', models.CharField(blank=True, default='', max_length=2000)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.customer')),
                ('deliverer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to=settings.AUTH_USER_MODEL)),
                ('logistic_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logistic_orders', to=settings.AUTH_USER_MODEL)),
                ('sale_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Order',
                'verbose_name_plural': 'Product Orders',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProductOrderProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.product')),
                ('product_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.productorder')),
            ],
            options={
                'verbose_name': 'historical Product Order Product',
                'verbose_name_plural': 'historical Product Order Products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productorder')),
            ],
            options={
                'verbose_name': 'Product Order Product',
                'verbose_name_plural': 'Product Order Products',
            },
        ),
    ]
