# Generated by Django 5.0.8 on 2024-08-10 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='deliverer_id',
            new_name='deliverer',
        ),
        migrations.RenameField(
            model_name='productorder',
            old_name='logistic_staff_id',
            new_name='logistic_staff',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_staff_id',
        ),
        migrations.AddField(
            model_name='productorder',
            name='sale_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sale_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
