# Generated by Django 4.2.15 on 2024-08-11 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='deliverer_id',
            new_name='deliverer',
        ),
        migrations.RenameField(
            model_name='productorder',
            old_name='logistic_staff_id',
            new_name='logistic_staff',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_staff_id',
        ),
        migrations.AddField(
            model_name='productorder',
            name='sale_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sale_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
