# Generated by Django 5.0.7 on 2024-09-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productorder",
            name="note",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
