# Generated by Django 4.2.15 on 2024-08-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
