# Generated by Django 5.0.7 on 2024-10-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcustomer",
            name="address",
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
