# Generated by Django 4.2.15 on 2024-08-13 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productorder_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorderproduct',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productorderproduct',
            old_name='product_orders',
            new_name='product_order',
        ),
    ]
