# Generated by Django 4.2.15 on 2024-08-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='isUrgent',
            field=models.BooleanField(choices=[(False, 'Not Urgent'), (True, 'Urgent')], default=False),
        ),
        migrations.CreateModel(
            name='ProductOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product_orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productorder')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='productorder',
            name='products',
            field=models.ManyToManyField(through='products.ProductOrderProduct', to='products.product'),
        ),
    ]
