# Generated by Django 4.2.15 on 2024-08-13 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_products_productorderproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorderproduct',
            name='product_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productorder'),
        ),
    ]
