# Generated by Django 5.0.7 on 2024-09-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_productorder_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="productorder",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
